//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace entityFrameworkMariaDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ability_effect
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ability_effect()
        {
            this.ability = new HashSet<ability>();
        }
    
        public string EffectName { get; set; }
        public byte ProcChance { get; set; }
        public Nullable<byte> TurnsAffected { get; set; }
        public Nullable<byte> DamagePerTurn { get; set; }
        public string EffectCategory { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ability> ability { get; set; }
        public virtual ability_effect_category ability_effect_category { get; set; }
    }
}
