//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace entityFrameworkMariaDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class caughtcreature_ability
    {
        public int CatchId { get; set; }
        public string AbilityName { get; set; }
        public int UseCount { get; set; }
    
        public virtual ability ability { get; set; }
        public virtual caughtcreature caughtcreature { get; set; }
    }
}
