//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace entityFrameworkMariaDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class creature_evolution
    {
        public string CreatureName { get; set; }
        public string EvolutionName { get; set; }
        public Nullable<int> EvolutionLevel { get; set; }
    
        public virtual creature creature { get; set; }
        public virtual creature evolution { get; set; }
    }
}
