//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace entityFrameworkMariaDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class entries
    {
        public int EntryID { get; set; }
        public string Title { get; set; }
        public string Text { get; set; }
        public System.DateTime date { get; set; }
        public string user { get; set; }
    
        public virtual users users { get; set; }
    }
}
