//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace entityFrameworkMariaDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class entriesdbEntities : DbContext
    {
        public entriesdbEntities()
            : base("name=entriesdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<entries> entries { get; set; }
        public virtual DbSet<files> files { get; set; }
        public virtual DbSet<users> users { get; set; }
        public virtual DbSet<newtesttable> newtesttable { get; set; }
    }
}
