//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace entityFrameworkMariaDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class trainer_battle
    {
        public int BattleId { get; set; }
        public string HostName { get; set; }
        public string OpponentName { get; set; }
        public string WinnerName { get; set; }
        public System.DateTime StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public string BattleStatus { get; set; }
    
        public virtual trainer trainer { get; set; }
        public virtual trainer trainer1 { get; set; }
        public virtual trainer trainer2 { get; set; }
    }
}
